insert into ramo_atividade (id, descricao) values (1, 'Distribuição de alimentos');
insert into ramo_atividade (id, descricao) values (2, 'Telecomunicações');
insert into ramo_atividade (id, descricao) values (3, 'Vestuário');
insert into ramo_atividade (id, descricao) values (4, 'Lavanderia');
insert into ramo_atividade (id, descricao) values (5, 'Gráfica');
insert into ramo_atividade (id, descricao) values (6, 'Mecânica');
insert into ramo_atividade (id, descricao) values (7, 'Turismo');
insert into ramo_atividade (id, descricao) values (8, 'Saúde');
insert into ramo_atividade (id, descricao) values (9, 'Educação');
insert into ramo_atividade (id, descricao) values (10, 'Lazer');
insert into ramo_atividade (id, descricao) values (11, 'Transporte');
insert into ramo_atividade (id, descricao) values (12, 'Construção Civil');
insert into ramo_atividade (id, descricao) values (13, 'Tecnologia da Informação');
insert into ramo_atividade (id, descricao) values (14, 'Automóveis');
insert into ramo_atividade (id, descricao) values (15, 'Farmácia');
insert into ramo_atividade (id, descricao) values (16, 'Cosméticos');
insert into ramo_atividade (id, descricao) values (17, 'Restaurante');
insert into ramo_atividade (id, descricao) values (18, 'Engenharia');
insert into ramo_atividade (id, descricao) values (19, 'Consultoria');
insert into ramo_atividade (id, descricao) values (20, 'Arquitetura');
insert into ramo_atividade (id, descricao) values (21, 'Supermercado');
insert into ramo_atividade (id, descricao) values (22, 'Cinema');
insert into ramo_atividade (id, descricao) values (23, 'Editora');
insert into ramo_atividade (id, descricao) values (24, 'Indústria Química');
insert into ramo_atividade (id, descricao) values (25, 'Logística');
insert into ramo_atividade (id, descricao) values (26, 'Comércio Exterior');
insert into ramo_atividade (id, descricao) values (27, 'Arte e Cultura');
insert into ramo_atividade (id, descricao) values (28, 'Publicidade');
insert into ramo_atividade (id, descricao) values (29, 'Hotelaria');
insert into ramo_atividade (id, descricao) values (30, 'Segurança');

insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (1, '70.311.193/0001-87', 'Mercado do João', 'João Mercado e Distribuidor de Alimentos Ltda', 'LTDA', '2009-03-02', 1);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (2, '52.822.994/0001-25', 'Fale Mais', 'Fale Mais Telecom S.A.', 'SA', '1997-12-10', 2);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (3, '41.952.519/0001-57', 'Maria de Souza da Silva', 'Maria de Souza da Silva', 'MEI', '2014-10-15', 3);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (4, '16.134.777/0001-89', 'Gomes Inovação', 'José Fernando Gomes EIRELI ME', 'EIRELI', '2009-03-02', 4);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (5, '99.876.543/0001-21', 'Moda Fashion', 'Moda Fashion Ltda', 'LTDA', '2010-08-18', 3);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (6, '11.222.333/0001-44', 'LavaBem', 'LavaBem Lavanderia EIRELI', 'EIRELI', '2011-06-30', 4);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (7, '77.888.999/0001-00', 'Gráfica Veloz', 'Gráfica Veloz SA', 'SA', '2005-11-20', 5);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (8, '33.444.555/0001-66', 'Oficina do Zé', 'Oficina do Zé Mecânica LTDA', 'LTDA', '2012-09-05', 6);
insert into empresa (id, cnpj, nome_fantasia, razao_social, tipo, data_fundacao, ramo_atividade_id) values (9, '12.345.678/0001-99', 'Viagens Turísticas', 'Viagens Turísticas SA', 'SA', '1999-02-28', 7);